//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace AFEI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class History : IDataErrorInfo
    {
        public int Id { get; set; }
        public float TransactionAmount { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public string Justification { get; set; }
        public string TransactionType { get; set; }
        public string error = "";
        public virtual Product Product { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual User User { get; set; }

        #region IDataErrorInfo Members

        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public string this[string columnName]
        {
            get
            {
                string result = null;
                if (columnName == "Quantity")
                {
                    if (Quantity == 0 || string.IsNullOrWhiteSpace(Quantity.ToString()))
                        result = "Favor ingresar una cantidad correcta";
                }
                if (columnName == "TransactionAmount")
                {
                    if (TransactionAmount == 0 || string.IsNullOrWhiteSpace(TransactionAmount.ToString()))
                        result = "Favor ingresar una cantidad correcta";
                }

                if (columnName == "Justification")
                {
                    if (string.IsNullOrWhiteSpace(Justification))
                    {
                        result = "Favor ingresar una justificacion";
                    }
                }

                error = result;
                return result;
            }

            #endregion
        }
    }
}
