//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFEI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Histories = new HashSet<History>();
            this.Clients = new HashSet<Client>();
            this.Prices = new HashSet<Price>();
            this.Providers = new HashSet<Provider>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
    
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
        public virtual ICollection<Provider> Providers { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
