//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using AFEI.Models;

namespace AFEI.Data
{
    public partial class AFEIEntities : ObjectContext
    {
        public const string ConnectionString = "name=AFEIEntities";
        public const string ContainerName = "AFEIEntities";
    
        #region Constructors
    
        public AFEIEntities()
            : base(ConnectionString, ContainerName)
        {
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        public AFEIEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        public AFEIEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<ChangesLog> ChangesLogs
        {
            get { return _changesLogs  ?? (_changesLogs = CreateObjectSet<ChangesLog>("ChangesLogs")); }
        }
        private ObjectSet<ChangesLog> _changesLogs;
    
        public ObjectSet<Client> Clients
        {
            get { return _clients  ?? (_clients = CreateObjectSet<Client>("Clients")); }
        }
        private ObjectSet<Client> _clients;
    
        public ObjectSet<History> Histories
        {
            get { return _histories  ?? (_histories = CreateObjectSet<History>("Histories")); }
        }
        private ObjectSet<History> _histories;
    
        public ObjectSet<Price> Prices
        {
            get { return _prices  ?? (_prices = CreateObjectSet<Price>("Prices")); }
        }
        private ObjectSet<Price> _prices;
    
        public ObjectSet<Product> Products
        {
            get { return _products  ?? (_products = CreateObjectSet<Product>("Products")); }
        }
        private ObjectSet<Product> _products;
    
        public ObjectSet<Provider> Providers
        {
            get { return _providers  ?? (_providers = CreateObjectSet<Provider>("Providers")); }
        }
        private ObjectSet<Provider> _providers;
    
        public ObjectSet<Transaction> Transactions
        {
            get { return _transactions  ?? (_transactions = CreateObjectSet<Transaction>("Transactions")); }
        }
        private ObjectSet<Transaction> _transactions;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;

        #endregion

    }
}
